// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByWrUhpnxkYYsFQ3wb9cLB3PSZMp1sTeQ',
    appId: '1:48309806360:web:385083da93785dbaa8ea6d',
    messagingSenderId: '48309806360',
    projectId: 'youtube-api-418916',
    authDomain: 'api-418916.firebaseapp.com',
    storageBucket: 'youtube-api-418916.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDiUSX-mgfzAL1iNrqRscO4WtcLx3Curc',
    appId: '1:48309806360:android:12a3fe24eeb92b30a8ea6d',
    messagingSenderId: '48309806360',
    projectId: 'youtube-api-418916',
    storageBucket: 'youtube-api-418916.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5_WX45GBtsqVuH9gZ_ZVk5YGpmXpa-nQ',
    appId: '1:48309806360:ios:883edc024afae5c8a8ea6d',
    messagingSenderId: '48309806360',
    projectId: 'youtube-api-418916',
    storageBucket: 'youtube-api-418916.firebasestorage.app',
    iosClientId: '48309806360-jl7sq0rii4dcquvqrqdkm1aj9gs33dad.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelPlan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5_WX45GBtsqVuH9gZ_ZVk5YGpmXpa-nQ',
    appId: '1:48309806360:ios:883edc024afae5c8a8ea6d',
    messagingSenderId: '48309806360',
    projectId: 'youtube-api-418916',
    storageBucket: 'youtube-api-418916.firebasestorage.app',
    iosClientId: '48309806360-jl7sq0rii4dcquvqrqdkm1aj9gs33dad.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelPlan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByWrUhpnxkYYsFQ3wb9cLB3PSZMp1sTeQ',
    appId: '1:48309806360:web:f75adccd409d88a0a8ea6d',
    messagingSenderId: '48309806360',
    projectId: 'youtube-api-418916',
    authDomain: 'api-418916.firebaseapp.com',
    storageBucket: 'youtube-api-418916.firebasestorage.app',
  );

}